steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_REPO_URL}/helloworld:$COMMIT_SHA',
    '-t', '${_REPO_URL}/helloworld:latest',
    '.'
  ]
images:
  - '${_REPO_URL}/helloworld:$COMMIT_SHA'
  - '${_REPO_URL}/helloworld:latest'
